config/routes.rb
Rails.application.routes.draw do
  resources :cars
  root 'cars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.haml
= form_for(car) do |f|
  - if car.errors.any?
    #error_explanation
      %h2
        = pluralize(car.errors.count, "error")
        prohibited this car from being saved:
      %ul
        - car.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :brand
    = f.text_field :brand
  .actions
    = f.submit

app/views/cars/edit.html.haml
%h1 Editing Car
= render 'form', car: @car
= link_to 'Show', @car
|
= link_to 'Back', cars_path

app/views/cars/index.html.haml
%p#notice= notice
%h1 See the console

%p Your @variables variable:
%code @variables =&gt; { "first_name":"bob" }
%br/
- @variables = { "first_name":"bob" }
%br/
= content_tag :div, '@variables', data: {filter: @variables}
%br/
%a.hitme{:href => "#"} See filter variables "stringified"
%br/
%br/
.filters

:javascript
  let filters = $('[data-filter]').data('filter')
  console.log(filters)
  $('.hitme').click((e) => {
    e.preventDefault()
    $('.filters').html(JSON.stringify(filters))
  })
  

app/views/cars/new.html.haml
%h1 New Car
= render 'form', car: @car
= link_to 'Back', cars_path

app/views/cars/show.html.haml
%p#notice= notice
%p
  %strong Brand:
  = @car.brand
= link_to 'Edit', edit_car_path(@car)
|
= link_to 'Back', cars_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wrapdata
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield